<#
.SYNOPSIS
    Builder script that compiles the init-mcp-git.ps1 script from template and embedded files.
    
.DESCRIPTION
    This script reads the init-mcp-git-template.ps1 file and embeds external file resources
    from the skills/ and .github/prompts/ directories to create the init-mcp-git.ps1 script.
    
.PARAMETER OutputFile
    The output file path for the compiled script (default: init-mcp-git.ps1)
    
.EXAMPLE
    .\build-init-script.ps1
    
.EXAMPLE
    .\build-init-script.ps1 -OutputFile "init-mcp-git-custom.ps1"
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$OutputFile = "init-mcp-git.ps1"
)

$ErrorActionPreference = "Stop"

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$TemplateFile = Join-Path $ScriptDir "init-mcp-git-template.ps1"

# Directories to embed
$ResourcesDir = Join-Path $ScriptDir "resources"

Write-Host "Building init-mcp-git script..." -ForegroundColor Cyan

# Verify template exists
if (-not (Test-Path $TemplateFile)) {
    Write-Host "ERROR: Template file not found: $TemplateFile" -ForegroundColor Red
    exit 1
}

# Function to recursively get all files in a directory with relative paths
function Get-FilesToEmbed {
    param(
        [string]$BaseDir,
        [string]$RelativeRoot
    )
    
    if (-not (Test-Path $BaseDir)) {
        Write-Warning "Directory not found: $BaseDir"
        return @()
    }
    
    $files = @()
    Get-ChildItem -Path $BaseDir -Recurse -File | ForEach-Object {
        $relativePath = $_.FullName.Substring($BaseDir.Length + 1)
        if ($RelativeRoot) {
            $relativePath = Join-Path $RelativeRoot $relativePath
        }
        $files += @{
            RelativePath = $relativePath
            FullPath = $_.FullName
            Content = Get-Content $_.FullName -Raw -Encoding UTF8
        }
    }
    
    return $files
}

# Collect files to embed
Write-Host "  Collecting files from resources/..." -ForegroundColor Gray
$allFiles = Get-FilesToEmbed -BaseDir $ResourcesDir -RelativeRoot ""

Write-Host "  Found $($allFiles.Count) files to embed" -ForegroundColor Gray

# Build the embedded files PowerShell structure
$embeddedFilesScript = @"
# Embedded Files - Generated by build-init-script.ps1
# DO NOT EDIT THIS SECTION MANUALLY
`$EmbeddedFiles = @(
"@

foreach ($file in $allFiles) {
    $content = $file.Content
    $embeddedFilesScript += @"

    @{
        RelativePath = "$($file.RelativePath -replace '\\', '\\')"
        Content = @'
$content
'@
    }
"@
}

$embeddedFilesScript += @"

)
# End of Embedded Files
"@

# Read template
Write-Host "  Reading template..." -ForegroundColor Gray
$templateContent = Get-Content $TemplateFile -Raw -Encoding UTF8

# Find and replace the placeholder
$placeholder = "# <<EMBEDDED_FILES_PLACEHOLDER>>"
if ($templateContent -notmatch [regex]::Escape($placeholder)) {
    Write-Host "ERROR: Template file does not contain the placeholder: $placeholder" -ForegroundColor Red
    exit 1
}

# Replace placeholder with embedded files
$outputContent = $templateContent -replace [regex]::Escape($placeholder), $embeddedFilesScript

# Write output file
Write-Host "  Writing output to: $OutputFile" -ForegroundColor Gray
$OutputFilePath = Join-Path $ScriptDir $OutputFile
$outputContent | Out-File -FilePath $OutputFilePath -Encoding utf8 -Force

Write-Host "✓ Build complete: $OutputFilePath" -ForegroundColor Green
Write-Host "  Embedded $($allFiles.Count) files" -ForegroundColor Gray
